### ISSUE TITLE
Update your python sdk to work with python version higher than 3.7

### ISSUE THREAD

**Issue by Marcus-Peterson** [serpapi/serpapi-python#14]
Fortunately for me, another project requires that i use 3.7 so it works fine there.
But another project requires that I use 3.9, so stuff like GoogleSearch(params) doesnt work now.
Update it thank you

I get these errors all the time now:
`ImportError: cannot import name 'GoogleSearch' from 'serpapi'`

**Comment by Freaky** [comment]
Hi Marcus, thanks for reporting this.

I believe you're looking for our older [`google-search-results`](https://github.com/serpapi/google-search-results-python) library.  Both it and this newer `serpapi` library have the same module name for imports, but different interfaces, so they're very easily confused.  We'll look into providing better error messages for this.

If you'd like to try using this library instead of `google-search-results`, its interface looks like this:

```python
import os
import serpapi

client = serpapi.Client(api_key=os.getenv("API_KEY"))
results = client.search(engine='google', q='coffee')
```

Further details can be found in the [README](https://github.com/serpapi/serpapi-python/blob/master/README.md).

Either client should work fine in Python 3.9 and beyond, regardless of which you choose to use going forward.

I hope that helps, and I'm sorry for the confusion.

**Comment by Marcus-Peterson** [comment]
Okay thanks, I'll look into this
